import{a as L,S as v,i as c}from"./assets/vendor-BPs2jpei.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();function f(t,r){const i=r.map(o=>`
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </a>
    `).join("");return t.insertAdjacentHTML("beforeend",i)}function S(t){t.innerHTML=""}class w{constructor(r,i){this.buttonEl=r,this.hiddenClass=i}hide(){this.buttonEl.classList.add(this.hiddenClass)}show(){this.buttonEl.classList.remove(this.hiddenClass)}disable(){this.buttonEl.disabled=!0}enable(){this.buttonEl.disabled=!1}}const E="https://pixabay.com/api/",q="45254861-458f9554e62e34626fe81458f";function u({page:t=1,per_page:r=15,q:i=""}={}){return L.get(E,{params:{page:t,per_page:r,q:i,key:q}}).then(({data:o})=>o)}const P=Object.freeze(Object.defineProperty({__proto__:null,getImages:u},Symbol.toStringTag,{value:"Module"})),d=document.querySelector(".gallery");document.querySelector("#button");const O=document.querySelector("#input"),m=document.querySelector("#search-form"),p=document.querySelector(".loader"),h=document.querySelector(".btn");console.log(P);function x(){p.classList.add("is-visible")}function g(){p.classList.remove("is-visible")}new v(".gallery a",{});const l=new w(h,"is-hidden");l.hide();const n={page:1,per_page:15,q:"",maxPage:0};m.addEventListener("submit",C);async function C(t){t.preventDefault(),S(d),n.q=O.value,console.log(n.q),x(),l.show(),l.disable(),n.page=1;try{const{hits:r,total:i}=await u(n);n.maxPage=Math.ceil(i/n.per_page),f(d,r),console.log(i);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;b(o),g(),n.maxPage>1?(l.enable(),h.addEventListener("click",y)):l.hide()}catch{c.error({title:"Error",message:"Error"})}finally{m.reset()}}async function y(){l.disable(),n.page+=1;try{const{hits:t}=await u(n);f(d,t),g();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;b(r)}catch{c.error({title:"Error",message:"Error"})}finally{n.page==n.maxPage?(l.hide(),h.removeEventListener("click",y),c.info({title:"End",message:"We are sorry, but you have reached the end of search results."})):l.enable()}}function b(t){window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
