import{a as v,S as L,i as d}from"./assets/vendor-BPs2jpei.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=i(e);fetch(e.href,n)}})();function p(t,r){const i=r.map(o=>`
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </a>
    `).join("");return t.insertAdjacentHTML("beforeend",i)}function w(t){t.innerHTML=""}class S{constructor(r,i){this.buttonEl=r,this.hiddenClass=i}hide(){this.buttonEl.classList.add(this.hiddenClass)}show(){this.buttonEl.classList.remove(this.hiddenClass)}disable(){this.buttonEl.disabled=!0}enable(){this.buttonEl.disabled=!1}}const E="https://pixabay.com/api/",q="45254861-458f9554e62e34626fe81458f";function m({page:t=1,per_page:r=15,q:i=""}={}){return v.get(E,{params:{page:t,per_page:r,q:i,key:q}}).then(({data:o})=>o)}const P=Object.freeze(Object.defineProperty({__proto__:null,getImages:m},Symbol.toStringTag,{value:"Module"})),u=document.querySelector(".gallery");document.querySelector("#button");const x=document.querySelector("#input"),g=document.querySelector("#search-form"),y=document.querySelector(".loader"),a=document.querySelector(".btn");console.log(P);function O(){y.classList.add("is-visible")}function h(){y.classList.remove("is-visible")}const C=new L(".gallery a",{}),l=new S(a,"is-hidden");l.hide();const s={page:1,per_page:15,q:"",maxPage:0};g.addEventListener("submit",$);async function $(t){t.preventDefault(),w(u),s.q=x.value.trim(),console.log(s.q),O(),l.show(),l.disable(),s.page=1;try{if(s.q=="")throw new Error;const{hits:r,total:i}=await m(s);s.maxPage=Math.ceil(i/s.per_page),p(u,r),C.refresh(),console.log(i);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;b(o),h(),s.maxPage>1?(l.enable(),a.addEventListener("click",f)):l.hide()}catch{d.error({title:"Error",message:"Error"}),h(),l.hide(),a.removeEventListener("click",f)}finally{g.reset()}}async function f(){l.disable(),s.page+=1;try{const{hits:t}=await m(s);p(u,t),h();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;b(r)}catch{d.error({title:"Error",message:"Error"})}finally{s.page==s.maxPage?(l.hide(),a.removeEventListener("click",f),d.info({title:"End",message:"We are sorry, but you have reached the end of search results."})):l.enable()}}function b(t){window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
